/**
 * BoardSim — Canonical shared types
 *
 * Generated from Phase 0 specification. Source of truth:
 *   _context/state-model.md
 *   _context/network-protocol.md
 *   _context/simulation-model.md
 *
 * Do not add types here that are not defined in those documents.
 * Changes to these types require updating the corresponding spec files.
 *
 * SYNC NOTE: This file is mirrored from frontend/types/index.ts.
 * Do not edit this file directly. Edit frontend/types/index.ts and copy.
 * Phase 2 will introduce a shared package to eliminate this duplication.
 */

// ============================================================
// Branded ID types
//
// IDs are nominal types — a PlayerId cannot be accidentally
// passed where a SceneId is expected. Cast from string using
// the `as` operator only at system boundaries (e.g. when
// receiving IDs from server payloads).
//
// Example:
//   const id = payload.playerId as PlayerId;
// ============================================================

declare const __brand: unique symbol;
type Brand<T, B extends string> = T & { readonly [__brand]: B };

export type PlayerId = Brand<string, "PlayerId">;
export type LobbyId  = Brand<string, "LobbyId">;
export type SceneId  = Brand<string, "SceneId">;
export type ObjectId = Brand<string, "ObjectId">;
export type AssetId  = Brand<string, "AssetId">;
export type GroupId  = Brand<string, "GroupId">;
export type StackId  = Brand<string, "StackId">;
export type EventId  = Brand<string, "EventId">;

// ============================================================
// Geometry
// ============================================================

export type Vector3 = {
  x: number;
  y: number;
  z: number;
};

export type Transform = {
  position: Vector3;
  rotation: Vector3;
  scale: Vector3;
};

// ============================================================
// Player
// ============================================================

export type Player = {
  id: PlayerId;
  displayName: string;
  connected: boolean;
  joinedAt: number;
};

// ============================================================
// Scene
//
// Scenes are logical containers (filters), not separate object
// collections. All objects share one flat world store and carry
// a sceneId field. See simulation-model.md — Scene Model Decision.
// ============================================================

export type SceneType = "public" | "private";

export type Scene = {
  id: SceneId;
  name: string;
  type: SceneType;
  /** Present only for private scenes */
  ownerId?: PlayerId;
  objectIds: ObjectId[];
};

// ============================================================
// Object capabilities
// ============================================================

export type ObjectCapabilities = {
  selectable: boolean;
  draggable: boolean;
  stackable: boolean;
  flippable: boolean;
  lockable: boolean;
  groupable: boolean;
};

// ============================================================
// Visibility
// ============================================================

export type VisibilityMode = "public" | "private" | "hidden";

export type VisibilityState = {
  mode: VisibilityMode;
  /** Player who owns private visibility */
  ownerId?: PlayerId;
  /** Additional players allowed to see the object */
  allowedPlayerIds?: PlayerId[];
};

// ============================================================
// Object lock
// ============================================================

export type ObjectLock = {
  ownerId: PlayerId;
  acquiredAt: number;
};

// ============================================================
// GameObject
//
// All interactive entities share a single generic model.
// There are no Card, Token, Board, or Piece classes in the core.
// ============================================================

export type GameObject = {
  id: ObjectId;
  sceneId: SceneId;
  assetId?: AssetId;
  transform: Transform;
  visibility: VisibilityState;
  capabilities: ObjectCapabilities;
  lock: ObjectLock | null;
  groupId?: GroupId;
  stackId?: StackId;
  metadata: Record<string, unknown>;
  createdAt: number;
  updatedAt: number;
};

// ============================================================
// Group
// ============================================================

export type ObjectGroup = {
  id: GroupId;
  objectIds: ObjectId[];
};

// ============================================================
// Stack
//
// An ordered collection of objects. index 0 = top of stack.
// ============================================================

export type ObjectStack = {
  id: StackId;
  sceneId: SceneId;
  /** Ordered list of object IDs. index 0 = top. */
  objectIds: ObjectId[];
};

// ============================================================
// Asset
// ============================================================

export type AssetType = "image" | "pdf" | "model";

export type AssetRole = "card" | "board" | "token" | "piece" | "other";

export type BuiltinResourceKey = "pawn" | "mat";

export type Asset = {
  id: AssetId;
  lobbyId: LobbyId;
  /** File format inferred from MIME type */
  type: AssetType;
  /** Game role assigned by the uploader */
  role: AssetRole;
  /** Display name — falls back to fileName if not provided */
  name: string;
  /** Original file name as uploaded */
  fileName: string;
  /** Player who uploaded this asset */
  uploadedBy: PlayerId;
  /** Served URL for the file, e.g. /uploads/[lobbyId]/[assetId].[ext] */
  source: string;
  /** Image pixel width (for images only) */
  imageWidth?: number;
  /** Image pixel height (for images only) */
  imageHeight?: number;
  createdAt: number;
};

// ============================================================
// Lobby
// ============================================================

export type LobbySettings = {
  maxPlayers: number;
};

export type LobbyInfo = {
  id: LobbyId;
  code: string;
  hostPlayerId: PlayerId;
  settings?: LobbySettings;
  createdAt: number;
};

export type LobbyState = LobbyInfo & {
  players: Record<PlayerId, Player>;
  scenes: Record<SceneId, Scene>;
  objects: Record<ObjectId, GameObject>;
  assets: Record<AssetId, Asset>;
  groups: Record<GroupId, ObjectGroup>;
  stacks: Record<StackId, ObjectStack>;
};

// ============================================================
// Snapshot
//
// Full state synchronization for join / reconnect / recovery.
// ============================================================

export type LobbySnapshot = {
  version: number;
  timestamp: number;
  lobby: LobbyInfo;
  players: Record<PlayerId, Player>;
  scenes: Record<SceneId, Scene>;
  objects: Record<ObjectId, GameObject>;
  assets: Record<AssetId, Asset>;
  groups: Record<GroupId, ObjectGroup>;
  stacks: Record<StackId, ObjectStack>;
};

// ============================================================
// Interaction State (client-only, never synchronized)
// ============================================================

export type InteractionType = "drag" | "rotate" | "scale";

export type ActiveInteraction = {
  objectId: ObjectId;
  type: InteractionType;
  startedAt: number;
};

export type InteractionState = {
  selectedObjectIds: ObjectId[];
  hoveredObjectId?: ObjectId;
  activeInteraction?: ActiveInteraction;
  pendingLockObjectId?: ObjectId;
};

// ============================================================
// UI State (client-only, never synchronized)
// ============================================================

export type ToolType =
  | "select"
  | "move"
  | "rotate"
  | "scale"
  | "group"
  | "lock"
  | "create"
  | "delete";

export type CameraState = {
  position: Vector3;
  zoom: number;
};

export type UIState = {
  activeTool: ToolType;
  activeSceneId: SceneId;
  assetPanelOpen: boolean;
  playerPanelOpen: boolean;
  camera: CameraState;
};

// ============================================================
// Network — Protocol version
// ============================================================

export type ProtocolInfo = {
  version: number;
};

// ============================================================
// Network — Event envelope (server → client)
// ============================================================

export type SimulationEvent<TPayload = unknown> = {
  version: number;
  id: EventId;
  sequence: number;
  type: string;
  playerId: PlayerId;
  timestamp: number;
  payload: TPayload;
};

// ============================================================
// Network — Client actions (client → server)
// ============================================================

export type CreateLobbyAction = {
  type: "CREATE_LOBBY";
  playerName: string;
  /**
   * Optional: provide the ID of a lobby already created via the HTTP API so the
   * Socket.IO gateway registers the same ID and all clients share one room.
   * When omitted the server generates a fresh ID.
   */
  lobbyId?: LobbyId;
  settings?: LobbySettings;
};

export type JoinLobbyAction = {
  type: "JOIN_LOBBY";
  lobbyId: LobbyId;
  playerName: string;
};

export type LeaveLobbyAction = {
  type: "LEAVE_LOBBY";
  lobbyId: LobbyId;
};

export type ReconnectLobbyAction = {
  type: "RECONNECT_LOBBY";
  lobbyId: LobbyId;
  playerId: PlayerId;
};

export type KickPlayerAction = {
  type: "KICK_PLAYER";
  lobbyId: LobbyId;
  playerId: PlayerId;
};

export type StartGameAction = {
  type: "START_GAME";
  lobbyId: LobbyId;
};

export type ObjectGrabRequestAction = {
  type: "OBJECT_GRAB_REQUEST";
  objectId: ObjectId;
};

export type PointerMoveAction = {
  type: "POINTER_MOVE";
  /** World-space pointer position on board (always sent). */
  position: Vector3;
  /** Optional object movement when actively dragging. */
  objectId?: ObjectId;
};

export type ObjectRotateRequestAction = {
  type: "OBJECT_ROTATE_REQUEST";
  objectId: ObjectId;
  rotation: Vector3;
};

export type ObjectScaleRequestAction = {
  type: "OBJECT_SCALE_REQUEST";
  objectId: ObjectId;
  scale: Vector3;
};

export type ObjectReleaseRequestAction = {
  type: "OBJECT_RELEASE_REQUEST";
  objectId: ObjectId;
};

export type CreateObjectSource =
  | {
      kind: "builtin";
      key: BuiltinResourceKey;
    }
  | {
      kind: "asset";
      assetId: AssetId;
    };

export type CreateObjectRequestAction = {
  type: "CREATE_OBJECT_REQUEST";
  sceneId: SceneId;
  position: Vector3;
  source: CreateObjectSource;
};

export type DeleteObjectRequestAction = {
  type: "DELETE_OBJECT_REQUEST";
  objectId: ObjectId;
};

export type DuplicateObjectRequestAction = {
  type: "DUPLICATE_OBJECT_REQUEST";
  objectId: ObjectId;
};

export type CreateGroupRequestAction = {
  type: "CREATE_GROUP_REQUEST";
  objectIds: ObjectId[];
};

export type UpdateGroupRequestAction = {
  type: "UPDATE_GROUP_REQUEST";
  groupId: GroupId;
  objectIds: ObjectId[];
};

export type DeleteGroupRequestAction = {
  type: "DELETE_GROUP_REQUEST";
  groupId: GroupId;
};

export type CreateStackRequestAction = {
  type: "CREATE_STACK_REQUEST";
  objectIds: ObjectId[];
};

export type SplitStackRequestAction = {
  type: "SPLIT_STACK_REQUEST";
  stackId: StackId;
  objectIds: ObjectId[];
};

export type MergeStackRequestAction = {
  type: "MERGE_STACK_REQUEST";
  sourceStackId: StackId;
  targetStackId: StackId;
};

export type ShuffleStackRequestAction = {
  type: "SHUFFLE_STACK_REQUEST";
  stackId: StackId;
};

export type FlipStackRequestAction = {
  type: "FLIP_STACK_REQUEST";
  stackId: StackId;
};

export type DrawStackRequestAction = {
  type: "DRAW_STACK_REQUEST";
  stackId: StackId;
  amount: number;
};

export type CreateSceneRequestAction = {
  type: "CREATE_SCENE_REQUEST";
  scene: Scene;
};

export type DeleteSceneRequestAction = {
  type: "DELETE_SCENE_REQUEST";
  sceneId: SceneId;
};

export type TransferObjectRequestAction = {
  type: "TRANSFER_OBJECT_REQUEST";
  objectId: ObjectId;
  sceneId: SceneId;
};

export type UpdateVisibilityRequestAction = {
  type: "UPDATE_VISIBILITY_REQUEST";
  objectId: ObjectId;
  visibility: VisibilityState;
};

export type RequestUploadUrlAction = {
  type: "REQUEST_UPLOAD_URL";
  role: AssetRole;
  /** Display name — server falls back to fileName if omitted */
  name?: string;
  fileName: string;
  mimeType: string;
  /** Image pixel width (for images only) */
  imageWidth?: number;
  /** Image pixel height (for images only) */
  imageHeight?: number;
};

export type DeleteAssetRequestAction = {
  type: "DELETE_ASSET_REQUEST";
  assetId: AssetId;
};

export type ClientAction =
  | CreateLobbyAction
  | JoinLobbyAction
  | LeaveLobbyAction
  | ReconnectLobbyAction
  | KickPlayerAction
  | ObjectGrabRequestAction
  | PointerMoveAction
  | ObjectRotateRequestAction
  | ObjectScaleRequestAction
  | ObjectReleaseRequestAction
  | CreateObjectRequestAction
  | DeleteObjectRequestAction
  | DuplicateObjectRequestAction
  | CreateGroupRequestAction
  | UpdateGroupRequestAction
  | DeleteGroupRequestAction
  | CreateStackRequestAction
  | SplitStackRequestAction
  | MergeStackRequestAction
  | ShuffleStackRequestAction
  | FlipStackRequestAction
  | DrawStackRequestAction
  | CreateSceneRequestAction
  | DeleteSceneRequestAction
  | TransferObjectRequestAction
  | UpdateVisibilityRequestAction
  | RequestUploadUrlAction
  | DeleteAssetRequestAction;

// ============================================================
// Network — Server events (server → client payloads)
// ============================================================

export type LobbyCreatedEvent = {
  type: "LOBBY_CREATED";
  lobby: LobbyInfo;
  player: Player;
};

export type LobbyJoinedEvent = {
  type: "LOBBY_JOINED";
  snapshot: LobbySnapshot;
  player: Player;
};

export type PlayerJoinedEvent = {
  type: "PLAYER_JOINED";
  player: Player;
};

export type PlayerLeftEvent = {
  type: "PLAYER_LEFT";
  playerId: PlayerId;
};

export type PlayerKickedEvent = {
  type: "PLAYER_KICKED";
  playerId: PlayerId;
};

export type HostChangedEvent = {
  type: "HOST_CHANGED";
  hostId: PlayerId;
};

export type GameStartedEvent = {
  type: "GAME_STARTED";
  lobbyId: LobbyId;
  lobbyCode: string;
};

export type ObjectGrabGrantedEvent = {
  type: "OBJECT_GRAB_GRANTED";
  objectId: ObjectId;
  playerId: PlayerId;
};

export type ObjectGrabRejectedEvent = {
  type: "OBJECT_GRAB_REJECTED";
  objectId: ObjectId;
  ownerId: PlayerId;
};

export type ObjectReleasedEvent = {
  type: "OBJECT_RELEASED";
  objectId: ObjectId;
};

export type ObjectCreatedEvent = {
  type: "OBJECT_CREATED";
  object: GameObject;
};

export type ObjectDeletedEvent = {
  type: "OBJECT_DELETED";
  objectId: ObjectId;
};

export type ObjectMovedEvent = {
  type: "OBJECT_MOVED";
  objectId: ObjectId;
  position: Vector3;
};

export type ObjectRotatedEvent = {
  type: "OBJECT_ROTATED";
  objectId: ObjectId;
  rotation: Vector3;
};

export type ObjectScaledEvent = {
  type: "OBJECT_SCALED";
  objectId: ObjectId;
  scale: Vector3;
};

export type VisibilityChangedEvent = {
  type: "VISIBILITY_CHANGED";
  objectId: ObjectId;
  visibility: VisibilityState;
};

export type GroupCreatedEvent = {
  type: "GROUP_CREATED";
  groupId: GroupId;
  objectIds: ObjectId[];
};

export type GroupUpdatedEvent = {
  type: "GROUP_UPDATED";
  groupId: GroupId;
  objectIds: ObjectId[];
};

export type GroupDeletedEvent = {
  type: "GROUP_DELETED";
  groupId: GroupId;
};

export type StackCreatedEvent = {
  type: "STACK_CREATED";
  stackId: StackId;
  objectIds: ObjectId[];
};

export type StackSplitEvent = {
  type: "STACK_SPLIT";
  sourceStackId: StackId;
  targetStackId: StackId;
  objectIds: ObjectId[];
};

export type StackMergedEvent = {
  type: "STACK_MERGED";
  sourceStackId: StackId;
  targetStackId: StackId;
};

export type StackShuffledEvent = {
  type: "STACK_SHUFFLED";
  stackId: StackId;
  /** Deterministic shuffle seed for replay compatibility */
  seed: string;
};

export type StackFlippedEvent = {
  type: "STACK_FLIPPED";
  stackId: StackId;
};

export type StackDrawnEvent = {
  type: "STACK_DRAWN";
  stackId: StackId;
  objectIds: ObjectId[];
};

export type SceneCreatedEvent = {
  type: "SCENE_CREATED";
  scene: Scene;
};

export type SceneDeletedEvent = {
  type: "SCENE_DELETED";
  sceneId: SceneId;
};

export type ObjectTransferredEvent = {
  type: "OBJECT_TRANSFERRED";
  objectId: ObjectId;
  sceneId: SceneId;
};

export type UploadUrlReadyEvent = {
  type: "UPLOAD_URL_READY";
  assetId: AssetId;
  /** One-time signed upload URL. POSTing a multipart/form-data 'file' field to
   * this URL completes the upload. Expires after 5 minutes. */
  uploadUrl: string;
};

export type AssetUploadedEvent = {
  type: "ASSET_UPLOADED";
  asset: Asset;
};

export type AssetDeletedEvent = {
  type: "ASSET_DELETED";
  assetId: AssetId;
};

export type CursorMovedEvent = {
  type: "CURSOR_MOVED";
  playerId: PlayerId;
  position: Vector3;
};

export type CursorPosition = {
  playerId: PlayerId;
  playerName: string;
  /** World-space XZ position on the board surface (y ≈ 0). */
  position: Vector3;
};

export type CursorsUpdateEvent = {
  type: "CURSORS_UPDATE";
  cursors: CursorPosition[];
};

export type ErrorCode =
  | "LOBBY_NOT_FOUND"
  | "LOBBY_FULL"
  | "INVALID_ACTION"
  | "INVALID_OBJECT"
  | "OBJECT_LOCKED"
  | "OBJECT_NOT_FOUND"
  | "ASSET_NOT_FOUND"
  | "PERMISSION_DENIED"
  | "INTERNAL_ERROR";

export type ErrorEvent = {
  type: "ERROR";
  code: ErrorCode;
  message: string;
};

export type ServerEvent =
  | LobbyCreatedEvent
  | LobbyJoinedEvent
  | PlayerJoinedEvent
  | PlayerLeftEvent
  | PlayerKickedEvent
  | HostChangedEvent
  | GameStartedEvent
  | ObjectGrabGrantedEvent
  | ObjectGrabRejectedEvent
  | ObjectReleasedEvent
  | ObjectCreatedEvent
  | ObjectDeletedEvent
  | ObjectMovedEvent
  | ObjectRotatedEvent
  | ObjectScaledEvent
  | VisibilityChangedEvent
  | GroupCreatedEvent
  | GroupUpdatedEvent
  | GroupDeletedEvent
  | StackCreatedEvent
  | StackSplitEvent
  | StackMergedEvent
  | StackShuffledEvent
  | StackFlippedEvent
  | StackDrawnEvent
  | SceneCreatedEvent
  | SceneDeletedEvent
  | ObjectTransferredEvent
  | UploadUrlReadyEvent
  | AssetUploadedEvent
  | AssetDeletedEvent
  | CursorMovedEvent
  | ErrorEvent;
